[versions]
android-plugin = "8.7.3"
kotlin-plugin = "2.1.0"

androidx-junit = "1.2.1"
androidx-espresso = "3.6.1"
androidx-appcompat = "1.7.0"
androidx-activity = "1.9.3"
androidx-lifecycle = "2.8.7"
androidx-compose-bom = "2024.11.00"

junit = "4.13.2"

glide = "1.0.0-beta01"
coil = "2.7.0"
coil3 = "3.0.4"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }

kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-plugin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin-plugin" }

matisse-android-application = { id = "matisse.android.application", version = "unspecified" }
matisse-android-library = { id = "matisse.android.library", version = "unspecified" }
matisse-android-compose = { id = "matisse.android.compose", version = "unspecified" }

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-plugin" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-plugin" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

junit = { module = "junit:junit", version.ref = "junit" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }

coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-gif = { module = "io.coil-kt.coil3:coil-gif", version.ref = "coil3" }
coil3-video = { module = "io.coil-kt.coil3:coil-video", version.ref = "coil3" }

glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glide" }