[versions]
android-plugin = "8.2.2"
kotlin-plugin = "1.9.22"
ksp-plugin = "1.9.22-1.0.17"

junit-junit = "4.13.2"
androidx-junit = "1.1.5"
androidx-espresso = "3.5.1"
androidx-appcompat = "1.6.1"
androidx-activity-compose = "1.8.2"
androidx-lifecycle-runtime-ktx = "2.7.0"

androidx-compose-bom = "2024.02.00"
androidx-compose-compiler = "1.5.9"

matisse-remote = "1.1.5"
matisse-publishing = "1.2.0-beta01"

coil = "2.5.0"

glide = "5.0.0-rc01"
glide-compose = "1.0.0-beta01"

zoom-image = "1.0.2"

zoomable-image = "0.8.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
android-library = { id = "com.android.library", version.ref = "android-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-plugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin-plugin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-plugin" }

matisse-android-application = { id = "matisse.android.application", version = "unspecified" }
matisse-android-library = { id = "matisse.android.library", version = "unspecified" }
matisse-android-compose = { id = "matisse.android.compose", version = "unspecified" }

[libraries]
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "android-plugin" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin-plugin" }

androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle-runtime-ktx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }

junit-junit = { module = "junit:junit", version.ref = "junit-junit" }

matisse = { module = "io.github.leavesczy:matisse", version.ref = "matisse-remote" }

coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-video = { module = "io.coil-kt:coil-video", version.ref = "coil" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide-compose = { module = "com.github.bumptech.glide:compose", version.ref = "glide-compose" }

zoom-image-coil = { module = "io.github.panpf.zoomimage:zoomimage-compose-coil", version.ref = "zoom-image" }
zoom-image-glide = { module = "io.github.panpf.zoomimage:zoomimage-compose-glide", version.ref = "zoom-image" }

zoomable-image-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "zoomable-image" }
zoomable-image-glide = { module = "me.saket.telephoto:zoomable-image-glide", version.ref = "zoomable-image" }